baseURL = "https://qinjo.github.io/Chinjo.Hugo/"
languageCode = "en-us"
title = "Chinjo"
theme = "archie"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=9 # articles per page

[params]
	favicon = "https://www.notion.so/jojodudu/874e08978e6242948d518485d21944d9?pvs=4#7f93339162ae4dbbbc375723f25abc42"
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "我的精简博客 -- [Chinjo.Hugo](https://github.com/qinjo/Chinjo.Hugo)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/qinjo/Chinjo.Hugo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
