baseURL = "https://qinjo.github.io/Chinjo.Hugo/"
languageCode = "en-us"
title = "Chinjo"
theme = "paper"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'https://github.com/qinjo'                 # github.com/YOUR_GITHUB_ID
  instagram = 'https://github.com/qinjo'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://raw.githubusercontent.com/qinjo/pic-private/main/picgo_pic/logo.png'                 # gravatar email or image url
  name = 'chin'
  bio = 'jo'

  # Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
