baseURL = "https://qinjo.github.io/Chinjo.Hugo/"
languageCode = "en-us"
title = "Chinjo"
theme = "paper"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'jodududu'               # twitter.com/YOUR_TWITTER_ID
  github = 'qinjo'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://raw.githubusercontent.com/qinjo/pic-private/main/picgo_pic/logo.png'                 # gravatar email or image url
  name = 'chin'
  bio = 'jo'

  # Main menu Items

[[menu.main]]
name = "Home"
url = "https://qinjo.github.io/Chinjo.Hugo"
weight = 1

[[menu.main]]
name = "All posts"
url = "https://qinjo.github.io/Chinjo.Hugo/posts"
weight = 2
